name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main branch'e push olunca çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/deryayildirimm/gaming-secure:1.0 .

      - name: Push Docker image
        run: |
          docker push ghcr.io/deryayildirimm/gaming-secure:1.0
