name: CD only • Trigger Render
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
